feat: test GA syntx

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -46,19 +46,22 @@ jobs:
             aws-region: us-east-1
         - name: Build docker image for service
           run: ./scripts/build.sh test $GIT_TAG true
-        - name: Set SLACK_MESSAGE
-          if: always()
-          run: |
-            [[ ${{ job.status }} == success ]] && echo "SLACK_MESSAGE=📦 Docker image *${{ env.REPO_NAME }}@${{ env.GIT_TAG }}* created! (by ${{ github.actor }})!" >> $GITHUB_ENV \
-                || echo "SLACK_MESSAGE=:red_circle: A Build Docker Image job has failed!" >> $GITHUB_ENV
-        - name: Slack Notification
-          uses: rtCamp/action-slack-notify@v2
-          if: always()
-          env:
-            SLACK_CHANNEL: es-test
-            SLACK_COLOR: ${{ job.status }}
-            SLACK_USERNAME: GitHub Action Releases
-            SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
+        - uses: ./.github/actions/slack
+          with:
             SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
-            SLACK_TITLE: 'Project: ${{ env.REPO_NAME }}'
-            MSG_MINIMAL: actions url,commit
+        # - name: Set SLACK_MESSAGE
+        #   if: always()
+        #   run: |
+        #     [[ ${{ job.status }} == success ]] && echo "SLACK_MESSAGE=📦 Docker image *${{ env.REPO_NAME }}@${{ env.GIT_TAG }}* created! (by ${{ github.actor }})!" >> $GITHUB_ENV \
+        #         || echo "SLACK_MESSAGE=:red_circle: A Build Docker Image job has failed!" >> $GITHUB_ENV
+        # - name: Slack Notification
+        #   uses: rtCamp/action-slack-notify@v2
+        #   if: always()
+        #   env:
+        #     SLACK_CHANNEL: es-test
+        #     SLACK_COLOR: ${{ job.status }}
+        #     SLACK_USERNAME: GitHub Action Releases
+        #     SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
+        #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+        #     SLACK_TITLE: 'Project: ${{ env.REPO_NAME }}'
+        #     MSG_MINIMAL: actions url,commit
